# ruler: draw a ruler on a canvas
canvas .c -width 12c -height 1.2c

pack .c

.c create line 1c 0.5c 1c 1c 11c 1c 11c 0.5c

for {set i 0} {$i < 10} {incr i} {
  set x [expr {$i + 1}]

  set l1 [.c create line ${x}c  1c ${x}c  0.6c]
  set l2 [.c create line $x.25c 1c $x.25c 0.6c]
  set l3 [.c create line $x.5c  1c $x.5c  0.7c]
  set l4 [.c create line $x.75c 1c $x.75c 0.8c]

  set t1 [.c create text $x.15c .75c -text $i -anchor sw]
}
