text .text -relief raised -bd 2 -yscrollcommand {.scroll set} -width 60 -height 40

scrollbar .scroll -command {.text yview}

grid .text   -row 0 -column 0 -sticky nsew
grid .scroll -row 0 -column 1 -sticky ns

grid rowconfigure    . 0 -weight 1
grid columnconfigure . 0 -weight 1

proc loadFile {file} {
  .text delete 1.0 end
  set f [open $file]
  .text insert end [read $f]
  close $f
}

loadFile Makefile

.text tag add lineTag 1.0 1.end

puts [.text tag ranges lineTag]
